backend:
  name: github                    # ← switch from git-gateway to github
  repo: sterlingcodes/uri-ga-church-web   # owner/repo **exactly** as it is on GitHub
  branch: main                    # keep the same deploy branch
  auth: /api/auth                 # Netlify proxy that handles the OAuth handshake

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Site Pages"
    files:
      - file: "src/pages/Home.jsx"
        label: "홈"
        name: "home"
        fields:
          - { label: "Title",      name: "title",      widget: "string" }
          - { label: "Hero Text",  name: "heroText",   widget: "text" }
          - { label: "Hero Image", name: "heroImage",  widget: "image" }
